### PR TITLE
Fix of first commit

### PR DESCRIPTION
**Pull request by WashingtonD**
Signed-off-by: Denys Shevchuk <dshev888@gmail.com>

### CODE REVIEW

**Review by MateuszSapala — APPROVED** [review]

**Review by magician1703 — APPROVED** [review]

**Comment by ArsenEloglian** [comment]
- Please compare your GitHub email address & your git config. (run:

git config --global user.name 
should return:
Denys Shevchuk
git config --global user.email
should return:
dshev888@gmail.com
)

- Read also StackOverflow and maybe you will be able to merge it from the command line.

https://stackoverflow.com/questions/55235047/github-merging-is-blocked-the-base-branch-requires-all-commits-to-be-signed

**Comment by ArsenEloglian** [comment]
image

**Comment by WashingtonD** [comment]
> * Please compare your GitHub email address & your git config. (run:
> 
> git config --global user.name should return: Denys Shevchuk git config --global user.email should return: [dshev888@gmail.com](mailto:dshev888@gmail.com) )
> 
> * Read also StackOverflow and maybe you will be able to merge it from the command line.
> 
> https://stackoverflow.com/questions/55235047/github-merging-is-blocked-the-base-branch-requires-all-commits-to-be-signed

Email adress and Name+Surname are the same in git config. Email adress is the same that is used for this github account. 
StackOverflow actions, which are basically try of merging from cmd aren't working properly

**Comment by ArsenEloglian** [comment]
> > * Please compare your GitHub email address & your git config. (run:
> > 
> > git config --global user.name should return: Denys Shevchuk git config --global user.email should return: [dshev888@gmail.com](mailto:dshev888@gmail.com) )
> > 
> > * Read also StackOverflow and maybe you will be able to merge it from the command line.
> > 
> > https://stackoverflow.com/questions/55235047/github-merging-is-blocked-the-base-branch-requires-all-commits-to-be-signed
> 
> Email adress and Name+Surname are the same in git config. Email adress is the same that is used for this github account. StackOverflow actions, which are basically try of merging from cmd aren't working properly

https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits

**Pull request closed without merging**
