### PR TITLE
Update AttendanceList.txt

### PR DESCRIPTION
**Pull request by Wegrzynk**

### CODE REVIEW

**Review by Admarx — APPROVED** [review]
test

**Review by baranskim — APPROVED** [review]

**Review by MateuszSapala — APPROVED** [review]
Test approve

**Comment by Wegrzynk** [comment]
Test worked perfectly.

**Comment by ArsenEloglian** [comment]
@Wegrzynk,  please close this PR with the test conclusion message.

**Comment by Wegrzynk** [comment]
This test PR proved that updating a given file requires the approval of the owner of the folder in which the file is located.

**Pull request closed without merging**
