### PR TITLE
lista obecnosci - 21.10.2022

### PR DESCRIPTION
**Pull request by barbara-k97**

### CODE REVIEW

**Review by KaroW97 — APPROVED** [review]

**Review by ArsenEloglian — CHANGES_REQUESTED** [review]
PR its not in a line with requirements.

**Review by markow1997 — APPROVED** [review]

**Comment by ArsenEloglian** [comment]
> Is it correct now?

image

It should contain only 1 commit & 1 file change :)

**Comment by barbara-k97** [comment]
At first I got a bit confused about how to do it and then I tried to correct it. Can I remove this pull requewst and add it again? Do we add the solved task in a separate pull request?

**Review by ArsenEloglian — CHANGES_REQUESTED** [review]
Please revert unnecessary changes.

**Comment by ArsenEloglian** [comment]
> At first I got a bit confused about how to do it and then I tried to correct it. Can I remove this pull requewst and add it again? Do we add the solved task in a separate pull request?

Keep calm ;)
Of course, you can delete this PR and create a new one, never mind.

for adding separate pull requests you need to create different branches, both from main, and then you can create new PR from every branch :)

**Pull request closed without merging**
