### PR TITLE
009.palindrome-number

### PR DESCRIPTION
**Pull request by magician1703**

### CODE REVIEW

**Review by barbara-k97 — APPROVED** [review]

**Review by ArsenEloglian — APPROVED** [review]

**Review by Monikazx — APPROVED** [review]

**Review by MateuszSapala — APPROVED** [review]

**Comment by ArsenEloglian** [comment]
@magician1703

**Comment by ArsenEloglian** [comment]
@magician1703

**Comment by ArsenEloglian** [comment]
@magician1703

**Comment by barbara-k97** [comment]
PR closed due to lack of activity.

**Pull request closed without merging**
