### PR TITLE
Zadanie pierwsze i uzupełnienie listy obecności 

### PR DESCRIPTION
**Pull request by Monikazx**

### CODE REVIEW

**Review by ArsenEloglian — APPROVED** [review]

**Review by barbara-k97 — APPROVED** [review]
approve

**Review by MateuszSapala — APPROVED** [review]

**Comment by Monikazx** [comment]
@ArsenEloglian 
- I generated ssh key and added it to ssh-agent (https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding- it-to-the-ssh-agent)
- I added it to my github account (https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)
- I set up the ssh key in git (https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key)

However, when I try to sign a commit, I get the following error:
error: Load key "C:\\Users\\Monika\\AppData\\Local\\Temp/.git_signing_key_tmpBtxMjT": invalid format?
fatal: failed to write commit object

Do you know how I can solve this problem?

**Comment by ArsenEloglian** [comment]
@Monikazx 
what is the status of this PR?

**Comment by ArsenEloglian** [comment]
> 

https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits

https://docs.github.com/en/authentication/troubleshooting-commit-signature-verification

**Comment by ArsenEloglian** [comment]
> > 
> 
> https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits
> 
> https://docs.github.com/en/authentication/troubleshooting-commit-signature-verification

The same problem has colleague @WashingtonD 
https://github.com/ArsenEloglian/AdvanceProgrammingTechniques_2223/pull/28

**Comment by ArsenEloglian** [comment]
image

**Pull request closed without merging**
