### PR TITLE
Update AttendanceList 28.10.2022

### PR DESCRIPTION
**Pull request by Monikazx**
Adding class attendance of 28.10.2022

Link to closed PR: https://github.com/ArsenEloglian/AdvanceProgrammingTechniques_2223/pull/105

### CODE REVIEW

**Review by barbara-k97 — APPROVED** [review]

**Review by Flehmango — APPROVED** [review]

**Comment by ArsenEloglian** [comment]
Linked PR has been created 04.11.2022. 
Please link the correct one.

**Comment by Monikazx** [comment]
> Linked PR has been created 04.11.2022. Please link the correct one.

I added all the attendance that day (from the beginning of the year) because I had problems with the git and did it during class time (you allowed it, but unfortunately I closed it). The previous pr contains only 3 first attendances https://github.com/ArsenEloglian/AdvanceProgrammingTechniques_2223/pull/43, so I wanted to ask if in the next pr I can add all the remaining attendances at one time.

**Review by Lun4t1c — APPROVED** [review]

**Review by MateuszSapala — APPROVED** [review]

**Comment by Monikazx** [comment]
> Linked PR has been created 04.11.2022. Please link the correct one.
@ArsenEloglian 
Can I add this date?

**Review by ArsenEloglian — APPROVED** [review]

**Comment by ArsenEloglian** [comment]
2 commits

**Pull request merged**
